config/routes.rb
Fettc::Application.routes.draw do
  root to: 'static_pages#home'

  get "static_pages/about"

  resources :comm_methods

  resources :users

  resources :notifications

end

app/models/comm_method.rb
class CommMethod < ActiveRecord::Base
  attr_accessible :address, :type, :user_id

  #belongs_to :user
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  attr_accessible :content, :post_date, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :is_admin, :name, :password
  
  has_many :comm_methods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comm_methods_controller.rb
class CommMethodsController < ApplicationController
  # GET /comm_methods
  # GET /comm_methods.json
  def index
    @comm_methods = CommMethod.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comm_methods }
    end
  end

  # GET /comm_methods/1
  # GET /comm_methods/1.json
  def show
    @comm_method = CommMethod.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comm_method }
    end
  end

  # GET /comm_methods/new
  # GET /comm_methods/new.json
  def new
    @comm_method = CommMethod.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comm_method }
    end
  end

  # GET /comm_methods/1/edit
  def edit
    @comm_method = CommMethod.find(params[:id])
  end

  # POST /comm_methods
  # POST /comm_methods.json
  def create
    @comm_method = CommMethod.new(params[:comm_method])

    respond_to do |format|
      if @comm_method.save
        format.html { redirect_to @comm_method, notice: 'Comm method was successfully created.' }
        format.json { render json: @comm_method, status: :created, location: @comm_method }
      else
        format.html { render action: "new" }
        format.json { render json: @comm_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comm_methods/1
  # PUT /comm_methods/1.json
  def update
    @comm_method = CommMethod.find(params[:id])

    respond_to do |format|
      if @comm_method.update_attributes(params[:comm_method])
        format.html { redirect_to @comm_method, notice: 'Comm method was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comm_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comm_methods/1
  # DELETE /comm_methods/1.json
  def destroy
    @comm_method = CommMethod.find(params[:id])
    @comm_method.destroy

    respond_to do |format|
      format.html { redirect_to comm_methods_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notifications }
    end
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
    @notification = Notification.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notification }
    end
  end

  # GET /notifications/new
  # GET /notifications/new.json
  def new
    @notification = Notification.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notification }
    end
  end

  # GET /notifications/1/edit
  def edit
    @notification = Notification.find(params[:id])
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(params[:notification])

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render json: @notification, status: :created, location: @notification }
      else
        format.html { render action: "new" }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notifications/1
  # PUT /notifications/1.json
  def update
    @notification = Notification.find(params[:id])

    respond_to do |format|
      if @notification.update_attributes(params[:notification])
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification = Notification.find(params[:id])
    @notification.destroy

    respond_to do |format|
      format.html { redirect_to notifications_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comm_methods_helper.rb
module CommMethodsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comm_methods/_form.html.erb
<%= form_for(@comm_method) do |f| %>
  <% if @comm_method.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comm_method.errors.count, "error") %> prohibited this comm_method from being saved:</h2>

      <ul>
      <% @comm_method.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comm_methods/edit.html.erb
<h1>Editing comm_method</h1>

<%= render 'form' %>

<%= link_to 'Show', @comm_method %> |
<%= link_to 'Back', comm_methods_path %>

app/views/comm_methods/index.html.erb
<h1>Listing comm_methods</h1>

<table>
  <tr>
    <th>Type</th>
    <th>Address</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comm_methods.each do |comm_method| %>
  <tr>
    <td><%= comm_method.type %></td>
    <td><%= comm_method.address %></td>
    <td><%= comm_method.user %></td>
    <td><%= link_to 'Show', comm_method %></td>
    <td><%= link_to 'Edit', edit_comm_method_path(comm_method) %></td>
    <td><%= link_to 'Destroy', comm_method, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comm method', new_comm_method_path %>

app/views/comm_methods/new.html.erb
<h1>New comm_method</h1>

<%= render 'form' %>

<%= link_to 'Back', comm_methods_path %>

app/views/comm_methods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Type:</b>
  <%= @comm_method.type %>
</p>

<p>
  <b>Address:</b>
  <%= @comm_method.address %>
</p>

<p>
  <b>User:</b>
  <%= @comm_method.user %>
</p>


<%= link_to 'Edit', edit_comm_method_path(@comm_method) %> |
<%= link_to 'Back', comm_methods_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fettc</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :post_date %><br />
    <%= f.date_select :post_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<h1>Listing notifications</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Post date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notifications.each do |notification| %>
  <tr>
    <td><%= notification.title %></td>
    <td><%= notification.content %></td>
    <td><%= notification.post_date %></td>
    <td><%= link_to 'Show', notification %></td>
    <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
    <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @notification.title %>
</p>

<p>
  <b>Content:</b>
  <%= @notification.content %>
</p>

<p>
  <b>Post date:</b>
  <%= @notification.post_date %>
</p>


<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>
<p>HEY HEY HEY</p>
<%= link_to "all users" users_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :is_admin %><br />
    <%= f.check_box :is_admin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Password</th>
    <th>Is admin</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= user.is_admin %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Is admin:</b>
  <%= @user.is_admin %>
</p>

<p>
  <b>Communication Methods</b>
  <%= @user.comm_methods %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>